# Generated by Django 6.0.5 on 2026-05-18 02:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=200)),
                ('telephone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('type_evenement', models.CharField(choices=[('mariage', 'Mariage'), ('anniversaire', 'Anniversaire'), ('bapteme', 'Baptême'), ('shooting', 'Shooting'), ('korite', 'Korité'), ('tabaski', 'Tabaski'), ('evenementiel', 'Événementiel'), ('autre', 'Autre')], max_length=50)),
                ('date_evenement', models.DateField()),
                ('heure_evenement', models.TimeField()),
                ('lieu', models.CharField(max_length=300)),
                ('nombre_personnes', models.IntegerField(blank=True, null=True)),
                ('budget', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('refused', 'Refusé'), ('cancelled', 'Annulé')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes_admin', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['-created_at'],
            },
        ),
    ]
