# Generated by Django 6.0.5 on 2026-05-18 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix_depart', models.IntegerField()),
                ('image', models.ImageField(blank=True, upload_to='services/')),
                ('details', models.JSONField(blank=True, default=list)),
                ('ordre', models.IntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Service',
                'ordering': ['ordre'],
            },
        ),
    ]
