# Generated by Django 6.0.5 on 2026-05-18 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Catégorie',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(blank=True, max_length=200)),
                ('image', models.ImageField(upload_to='portfolio/')),
                ('description', models.TextField(blank=True)),
                ('featured', models.BooleanField(default=False)),
                ('ordre', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Photo',
                'ordering': ['ordre', '-created_at'],
            },
        ),
    ]
